AquaWorld/AquaWorld.Web/Controllers/AdminController.cs
using AquaWorld.Data.Models;
using AquaWorld.Data.Services.Contracts;
using Bytes2you.Validation;
using System.Web.Mvc;

namespace AquaWorld.Web.Controllers
{
    public class AdminController : Controller
    {
        private readonly ICreatureService creatureService;
        private readonly IOrderService orderService;

        public AdminController(ICreatureService creatureService, IOrderService orderService)
        {
            Guard.WhenArgument(creatureService, "creatureService").IsNull().Throw();
            Guard.WhenArgument(orderService, "orderService").IsNull().Throw();

            this.creatureService = creatureService;
            this.orderService = orderService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddCreature()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCreature([Bind(Include = "Id,Name,Category,Description,AvailableCount,ImageUrl")] Creature creature)
        {
            if (ModelState.IsValid)
            {
                this.creatureService.Create(creature);
                return RedirectToAction("Index");
            }

            return View(creature);
        }

        public ActionResult CheckOrders()
        {
            return View(this.orderService.GetAllOrders());
        }

        public ActionResult ProceedOrderById(int orderId)
        {
            this.orderService.ProceedOrderById(orderId);
            return RedirectToAction("CheckOrders");
        }
    }
}

AquaWorld/AquaWorld.Web/Controllers/CreaturesController.cs
using AquaWorld.Data.Services.Contracts;
using AquaWorld.Web.Models;
using Bytes2you.Validation;
using System.Linq;
using System.Web.Mvc;

namespace AquaWorld.Web.Controllers
{
    public class CreaturesController : Controller
    {
        private readonly ICreatureService creatureService;

        public CreaturesController(ICreatureService creatureService)
        {
            Guard.WhenArgument(creatureService, "creatureService").IsNull().Throw();

            this.creatureService = creatureService;
        }

        public ActionResult Index()
        {
            var allCreatures = this.creatureService.GetAllCreatures().ToList().Select(c=> new CreatureViewModel(c)).ToList();
            return View(allCreatures);
        }

        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                var targetCreature = this.creatureService.GetCreatureById((int)id);

                return View(targetCreature);
            }
            else
            {
                return View(this.creatureService.GetAllCreatures().First());
            }
        }
    }
}

AquaWorld/AquaWorld.Web/Controllers/OrderController.cs
using AquaWorld.Data.Models;
using AquaWorld.Data.Services.Contracts;
using AquaWorld.Web.Models;
using Bytes2you.Validation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AquaWorld.Web.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;

        public OrderController(IOrderService orderService)
        {
            Guard.WhenArgument(orderService, "orderService").IsNull().Throw();

            this.orderService = orderService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(string userId)
        {
            var creaturesList = new List<Creature>();

            if (Session["CartItems"] != null)
            {
                var cartItems = Session["CartItems"] as List<Creature>;
                for (int i = 0; i < cartItems.Count; i++)
                {
                    if (creaturesList.Any(c => c.Id == cartItems[i].Id))
                    {
                        var targetCreature = creaturesList.First(c => c.Id == cartItems[i].Id);
                        targetCreature.OrderedItemsCount += 1;
                    }
                    else
                    {
                        cartItems[i].OrderedItemsCount = 1;
                        creaturesList.Add(cartItems[i]);
                    }
                }
                Session["CartItems"] = null;
            }

            bool isSuccess = this.orderService.CreateOrder(userId, creaturesList);

            return isSuccess ? RedirectToAction("Index") : RedirectToAction("OutOfStock");
        }

        public ActionResult MyOrders(string id)
        {
            var cuurrentUsersOrders = this.orderService.GetOrdersByUserId(id).ToList().Select(o => new OrderViewModel(o)).ToList();
            return View(cuurrentUsersOrders);
        }
    }
}

AquaWorld/AquaWorld.Web/Views/Shared/BadRequest.cshtml
@{
    ViewBag.Title = "BadRequest";
}

<p><img style="max-height:500px; width:100%" src="https://t3.ftcdn.net/jpg/00/75/19/80/240_F_75198006_0VnAbG8hVa96eCIlApGsdvtF34kX2Nws.jpg" /></p>

AquaWorld/AquaWorld.Web/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<p><img style="max-height:500px; width:100%" src="https://hdimagesnew.com/wp-content/uploads/2016/09/404.png" /></p>

AquaWorld/AquaWorld.Web/Views/Shared/ServerError.cshtml
@{
    ViewBag.Title = "ServerError";
}

<div class="jumbotron" style="text-align:center; background-color: rgba(255, 255, 255, 0.8)">
    <p><img style="min-height:500px" src="https://t4.ftcdn.net/jpg/00/75/19/79/240_F_75197993_ACVwnhYzRIIpu9JRPqjzsCYt5bjpYFUY.jpg" /></p>
</div>

AquaWorld/AquaWorld.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @using Microsoft.AspNet.Identity
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div style="padding-right:0px;padding-left:0px">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Aqua World", "Index", "Home", new { area = string.Empty }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Catalogue", "Index", "Creatures", new { area = string.Empty }, null)</li>

                    @{
                        if (User.IsInRole("admin"))
                        {
                            <li>@Html.ActionLink("Admin part", "Index", "Admin")</li>
                        }
                    }

                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right" style="margin-top: 0px; margin-left: 15px; display: table-row">
                        <li><a href="/ShoppingCart"><span class="glyphicon glyphicon-shopping-cart">Cart</span></a></li>
                        <li>@Html.ActionLink("My Orders", "MyOrders", "Order", new { area = string.Empty, @id = User.Identity.GetUserId() }, null)</li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div style="background-image: url('../../Images/underWater.jpeg'); background-size: 100% 100%; background-attachment: fixed; min-height: 590px;">
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer class="navbar navbar-inverse navbar-fixed-bottom">
                <ul class="nav navbar-nav">
                    @*<li>&copy; @DateTime.Now.Year - My ASP.NET Application</li>*@
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = string.Empty }, null)</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = string.Empty }, null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = string.Empty }, null)</li>
                </ul>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>